import "./globals.css";
import Header from "@/components/utils/header";
import Navigation from "@/components/utils/navigation";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

const notoSansJp = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Pint",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={`${notoSansJp.className} antialiased`}>
				<div className="flex h-screen w-screen flex-1 flex-col bg-stone-100">
					<Header />
					<main className="h-0 w-full grow overflow-y-auto">
						{children}
					</main>
					<Navigation />
				</div>
			</body>
		</html>
	);
}
